// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: users/service.proto

package users

import (
	common "warns/pkg/models/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_Blocked   Role = 0
	Role_Normal    Role = 1
	Role_Moderator Role = 2
	Role_Creator   Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "Blocked",
		1: "Normal",
		2: "Moderator",
		3: "Creator",
	}
	Role_value = map[string]int32{
		"Blocked":   0,
		"Normal":    1,
		"Moderator": 2,
		"Creator":   3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_users_service_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_users_service_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Credits        int64                  `protobuf:"varint,2,opt,name=credits,proto3" json:"credits,omitempty"`
	Stocks         int64                  `protobuf:"varint,3,opt,name=stocks,proto3" json:"stocks,omitempty"`
	Role           Role                   `protobuf:"varint,5,opt,name=role,proto3,enum=users.Role" json:"role,omitempty"`
	AutoBuyEnabled bool                   `protobuf:"varint,8,opt,name=autoBuyEnabled,proto3" json:"autoBuyEnabled,omitempty"`
	LastFarmingAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=lastFarmingAt,proto3" json:"lastFarmingAt,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_users_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *User) GetStocks() int64 {
	if x != nil {
		return x.Stocks
	}
	return 0
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_Blocked
}

func (x *User) GetAutoBuyEnabled() bool {
	if x != nil {
		return x.AutoBuyEnabled
	}
	return false
}

func (x *User) GetLastFarmingAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFarmingAt
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_users_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTopUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      common.Currency        `protobuf:"varint,1,opt,name=currency,proto3,enum=common.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUsers) Reset() {
	*x = GetTopUsers{}
	mi := &file_users_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsers) ProtoMessage() {}

func (x *GetTopUsers) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsers.ProtoReflect.Descriptor instead.
func (*GetTopUsers) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopUsers) GetCurrency() common.Currency {
	if x != nil {
		return x.Currency
	}
	return common.Currency(0)
}

type RepeatedUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedUsers) Reset() {
	*x = RepeatedUsers{}
	mi := &file_users_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedUsers) ProtoMessage() {}

func (x *RepeatedUsers) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedUsers.ProtoReflect.Descriptor instead.
func (*RepeatedUsers) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatedUsers) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      common.Currency        `protobuf:"varint,3,opt,name=currency,proto3,enum=common.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTransaction) Reset() {
	*x = UserTransaction{}
	mi := &file_users_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTransaction) ProtoMessage() {}

func (x *UserTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTransaction.ProtoReflect.Descriptor instead.
func (*UserTransaction) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{4}
}

func (x *UserTransaction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserTransaction) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UserTransaction) GetCurrency() common.Currency {
	if x != nil {
		return x.Currency
	}
	return common.Currency(0)
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *UserTransaction       `protobuf:"bytes,1,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	Receiver      *UserTransaction       `protobuf:"bytes,2,opt,name=receiver,proto3,oneof" json:"receiver,omitempty"`
	Type          common.TransactionType `protobuf:"varint,3,opt,name=type,proto3,enum=common.TransactionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_users_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionRequest) GetSender() *UserTransaction {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *TransactionRequest) GetReceiver() *UserTransaction {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *TransactionRequest) GetType() common.TransactionType {
	if x != nil {
		return x.Type
	}
	return common.TransactionType(0)
}

type SuccessfulTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessfulTransaction) Reset() {
	*x = SuccessfulTransaction{}
	mi := &file_users_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessfulTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessfulTransaction) ProtoMessage() {}

func (x *SuccessfulTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessfulTransaction.ProtoReflect.Descriptor instead.
func (*SuccessfulTransaction) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{6}
}

func (x *SuccessfulTransaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FailedTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Error           *common.Failure        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	TransactionType int64                  `protobuf:"varint,2,opt,name=transactionType,proto3" json:"transactionType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FailedTransaction) Reset() {
	*x = FailedTransaction{}
	mi := &file_users_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedTransaction) ProtoMessage() {}

func (x *FailedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedTransaction.ProtoReflect.Descriptor instead.
func (*FailedTransaction) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{7}
}

func (x *FailedTransaction) GetError() *common.Failure {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *FailedTransaction) GetTransactionType() int64 {
	if x != nil {
		return x.TransactionType
	}
	return 0
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *SuccessfulTransaction `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Failure       *FailedTransaction     `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	Transaction   *TransactionRequest    `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_users_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionResponse) GetSuccess() *SuccessfulTransaction {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *TransactionResponse) GetFailure() *FailedTransaction {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *TransactionResponse) GetTransaction() *TransactionRequest {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender        *UserTransaction       `protobuf:"bytes,2,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	Receiver      *UserTransaction       `protobuf:"bytes,3,opt,name=receiver,proto3,oneof" json:"receiver,omitempty"`
	Type          common.TransactionType `protobuf:"varint,4,opt,name=type,proto3,enum=common.TransactionType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_users_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{9}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetSender() *UserTransaction {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Transaction) GetReceiver() *UserTransaction {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Transaction) GetType() common.TransactionType {
	if x != nil {
		return x.Type
	}
	return common.TransactionType(0)
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TransactionHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionHistory) Reset() {
	*x = TransactionHistory{}
	mi := &file_users_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHistory) ProtoMessage() {}

func (x *TransactionHistory) ProtoReflect() protoreflect.Message {
	mi := &file_users_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHistory.ProtoReflect.Descriptor instead.
func (*TransactionHistory) Descriptor() ([]byte, []int) {
	return file_users_service_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionHistory) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_users_service_proto protoreflect.FileDescriptor

const file_users_service_proto_rawDesc = "" +
	"\n" +
	"\x13users/service.proto\x12\x05users\x1a\x12common/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acredits\x18\x02 \x01(\x03R\acredits\x12\x16\n" +
	"\x06stocks\x18\x03 \x01(\x03R\x06stocks\x12\x1f\n" +
	"\x04role\x18\x05 \x01(\x0e2\v.users.RoleR\x04role\x12&\n" +
	"\x0eautoBuyEnabled\x18\b \x01(\bR\x0eautoBuyEnabled\x12@\n" +
	"\rlastFarmingAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastFarmingAt\x128\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\vGetTopUsers\x12,\n" +
	"\bcurrency\x18\x01 \x01(\x0e2\x10.common.CurrencyR\bcurrency\"2\n" +
	"\rRepeatedUsers\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.users.UserR\x05users\"p\n" +
	"\x0fUserTransaction\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12,\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x10.common.CurrencyR\bcurrency\"\xc7\x01\n" +
	"\x12TransactionRequest\x123\n" +
	"\x06sender\x18\x01 \x01(\v2\x16.users.UserTransactionH\x00R\x06sender\x88\x01\x01\x127\n" +
	"\breceiver\x18\x02 \x01(\v2\x16.users.UserTransactionH\x01R\breceiver\x88\x01\x01\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.common.TransactionTypeR\x04typeB\t\n" +
	"\a_senderB\v\n" +
	"\t_receiver\"'\n" +
	"\x15SuccessfulTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"d\n" +
	"\x11FailedTransaction\x12%\n" +
	"\x05error\x18\x01 \x01(\v2\x0f.common.FailureR\x05error\x12(\n" +
	"\x0ftransactionType\x18\x02 \x01(\x03R\x0ftransactionType\"\xe0\x01\n" +
	"\x13TransactionResponse\x12;\n" +
	"\asuccess\x18\x01 \x01(\v2\x1c.users.SuccessfulTransactionH\x00R\asuccess\x88\x01\x01\x127\n" +
	"\afailure\x18\x02 \x01(\v2\x18.users.FailedTransactionH\x01R\afailure\x88\x01\x01\x12;\n" +
	"\vtransaction\x18\x03 \x01(\v2\x19.users.TransactionRequestR\vtransactionB\n" +
	"\n" +
	"\b_successB\n" +
	"\n" +
	"\b_failure\"\x8a\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x123\n" +
	"\x06sender\x18\x02 \x01(\v2\x16.users.UserTransactionH\x00R\x06sender\x88\x01\x01\x127\n" +
	"\breceiver\x18\x03 \x01(\v2\x16.users.UserTransactionH\x01R\breceiver\x88\x01\x01\x12+\n" +
	"\x04type\x18\x04 \x01(\x0e2\x17.common.TransactionTypeR\x04type\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\t\n" +
	"\a_senderB\v\n" +
	"\t_receiver\"L\n" +
	"\x12TransactionHistory\x126\n" +
	"\ftransactions\x18\x01 \x03(\v2\x12.users.TransactionR\ftransactions*;\n" +
	"\x04Role\x12\v\n" +
	"\aBlocked\x10\x00\x12\n" +
	"\n" +
	"\x06Normal\x10\x01\x12\r\n" +
	"\tModerator\x10\x02\x12\v\n" +
	"\aCreator\x10\x032\x87\x04\n" +
	"\x05Users\x12H\n" +
	"\x0fSendTransaction\x12\x19.users.TransactionRequest\x1a\x1a.users.TransactionResponse\x12,\n" +
	"\rChangeAutoBuy\x12\t.users.Id\x1a\x10.common.Response\x12#\n" +
	"\x06Create\x12\f.common.Void\x1a\v.users.User\x12!\n" +
	"\aGetUser\x12\t.users.Id\x1a\v.users.User\x122\n" +
	"\x06GetTop\x12\x12.users.GetTopUsers\x1a\x14.users.RepeatedUsers\x12,\n" +
	"\x06GetAll\x12\f.common.Void\x1a\x14.users.RepeatedUsers\x12/\n" +
	"\x0eGetTransaction\x12\t.users.Id\x1a\x12.users.Transaction\x12=\n" +
	"\x15GetTransactionHistory\x12\t.users.Id\x1a\x19.users.TransactionHistory\x12=\n" +
	"\x12GetAllTransactions\x12\f.common.Void\x1a\x19.users.TransactionHistory\x12-\n" +
	"\x04Farm\x12\t.users.Id\x1a\x1a.users.TransactionResponseB\tZ\a./usersb\x06proto3"

var (
	file_users_service_proto_rawDescOnce sync.Once
	file_users_service_proto_rawDescData []byte
)

func file_users_service_proto_rawDescGZIP() []byte {
	file_users_service_proto_rawDescOnce.Do(func() {
		file_users_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_service_proto_rawDesc), len(file_users_service_proto_rawDesc)))
	})
	return file_users_service_proto_rawDescData
}

var file_users_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_users_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_users_service_proto_goTypes = []any{
	(Role)(0),                     // 0: users.Role
	(*User)(nil),                  // 1: users.User
	(*Id)(nil),                    // 2: users.Id
	(*GetTopUsers)(nil),           // 3: users.GetTopUsers
	(*RepeatedUsers)(nil),         // 4: users.RepeatedUsers
	(*UserTransaction)(nil),       // 5: users.UserTransaction
	(*TransactionRequest)(nil),    // 6: users.TransactionRequest
	(*SuccessfulTransaction)(nil), // 7: users.SuccessfulTransaction
	(*FailedTransaction)(nil),     // 8: users.FailedTransaction
	(*TransactionResponse)(nil),   // 9: users.TransactionResponse
	(*Transaction)(nil),           // 10: users.Transaction
	(*TransactionHistory)(nil),    // 11: users.TransactionHistory
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(common.Currency)(0),          // 13: common.Currency
	(common.TransactionType)(0),   // 14: common.TransactionType
	(*common.Failure)(nil),        // 15: common.Failure
	(*common.Void)(nil),           // 16: common.Void
	(*common.Response)(nil),       // 17: common.Response
}
var file_users_service_proto_depIdxs = []int32{
	0,  // 0: users.User.role:type_name -> users.Role
	12, // 1: users.User.lastFarmingAt:type_name -> google.protobuf.Timestamp
	12, // 2: users.User.createdAt:type_name -> google.protobuf.Timestamp
	13, // 3: users.GetTopUsers.currency:type_name -> common.Currency
	1,  // 4: users.RepeatedUsers.users:type_name -> users.User
	13, // 5: users.UserTransaction.currency:type_name -> common.Currency
	5,  // 6: users.TransactionRequest.sender:type_name -> users.UserTransaction
	5,  // 7: users.TransactionRequest.receiver:type_name -> users.UserTransaction
	14, // 8: users.TransactionRequest.type:type_name -> common.TransactionType
	15, // 9: users.FailedTransaction.error:type_name -> common.Failure
	7,  // 10: users.TransactionResponse.success:type_name -> users.SuccessfulTransaction
	8,  // 11: users.TransactionResponse.failure:type_name -> users.FailedTransaction
	6,  // 12: users.TransactionResponse.transaction:type_name -> users.TransactionRequest
	5,  // 13: users.Transaction.sender:type_name -> users.UserTransaction
	5,  // 14: users.Transaction.receiver:type_name -> users.UserTransaction
	14, // 15: users.Transaction.type:type_name -> common.TransactionType
	12, // 16: users.Transaction.createdAt:type_name -> google.protobuf.Timestamp
	10, // 17: users.TransactionHistory.transactions:type_name -> users.Transaction
	6,  // 18: users.Users.SendTransaction:input_type -> users.TransactionRequest
	2,  // 19: users.Users.ChangeAutoBuy:input_type -> users.Id
	16, // 20: users.Users.Create:input_type -> common.Void
	2,  // 21: users.Users.GetUser:input_type -> users.Id
	3,  // 22: users.Users.GetTop:input_type -> users.GetTopUsers
	16, // 23: users.Users.GetAll:input_type -> common.Void
	2,  // 24: users.Users.GetTransaction:input_type -> users.Id
	2,  // 25: users.Users.GetTransactionHistory:input_type -> users.Id
	16, // 26: users.Users.GetAllTransactions:input_type -> common.Void
	2,  // 27: users.Users.Farm:input_type -> users.Id
	9,  // 28: users.Users.SendTransaction:output_type -> users.TransactionResponse
	17, // 29: users.Users.ChangeAutoBuy:output_type -> common.Response
	1,  // 30: users.Users.Create:output_type -> users.User
	1,  // 31: users.Users.GetUser:output_type -> users.User
	4,  // 32: users.Users.GetTop:output_type -> users.RepeatedUsers
	4,  // 33: users.Users.GetAll:output_type -> users.RepeatedUsers
	10, // 34: users.Users.GetTransaction:output_type -> users.Transaction
	11, // 35: users.Users.GetTransactionHistory:output_type -> users.TransactionHistory
	11, // 36: users.Users.GetAllTransactions:output_type -> users.TransactionHistory
	9,  // 37: users.Users.Farm:output_type -> users.TransactionResponse
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_users_service_proto_init() }
func file_users_service_proto_init() {
	if File_users_service_proto != nil {
		return
	}
	file_users_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_users_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_users_service_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_service_proto_rawDesc), len(file_users_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_service_proto_goTypes,
		DependencyIndexes: file_users_service_proto_depIdxs,
		EnumInfos:         file_users_service_proto_enumTypes,
		MessageInfos:      file_users_service_proto_msgTypes,
	}.Build()
	File_users_service_proto = out.File
	file_users_service_proto_goTypes = nil
	file_users_service_proto_depIdxs = nil
}
