// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: common/types.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_NoneCurrency Currency = 0
	Currency_Credits      Currency = 1
	Currency_Stocks       Currency = 2
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "NoneCurrency",
		1: "Credits",
		2: "Stocks",
	}
	Currency_value = map[string]int32{
		"NoneCurrency": 0,
		"Credits":      1,
		"Stocks":       2,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

type TransactionType int32

const (
	// Easy
	TransactionType_Get      TransactionType = 0 // Get
	TransactionType_Set      TransactionType = 1 // Set
	TransactionType_Transfer TransactionType = 2 // Transfer to other user
	TransactionType_Purchase TransactionType = 3 // Purchase
	TransactionType_Farm     TransactionType = 4 // Farm credits
	// Roles
	TransactionType_Block     TransactionType = 5 // Setting role to blocked
	TransactionType_User      TransactionType = 6 // Setting role to user
	TransactionType_Moderator TransactionType = 7 // Setting role to moderator
	// Warns
	TransactionType_Warn         TransactionType = 8
	TransactionType_InActiveWarn TransactionType = 9
	// Bans
	TransactionType_Ban         TransactionType = 10
	TransactionType_InActiveBan TransactionType = 11
	// Promos
	TransactionType_CreatePromoCode                 TransactionType = 12
	TransactionType_DeletePromoCode                 TransactionType = 13
	TransactionType_ActivatePromoCode               TransactionType = 14
	TransactionType_AddUsesForPromo                 TransactionType = 15
	TransactionType_AddTimeForPromo                 TransactionType = 16
	TransactionType_DecrementUsesPromo              TransactionType = 17
	TransactionType_AddActivationPromoCodeToHistory TransactionType = 18
	// Checks
	TransactionType_CreateCheck TransactionType = 19
	TransactionType_UseCheck    TransactionType = 20
	TransactionType_DeleteCheck TransactionType = 21
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0:  "Get",
		1:  "Set",
		2:  "Transfer",
		3:  "Purchase",
		4:  "Farm",
		5:  "Block",
		6:  "User",
		7:  "Moderator",
		8:  "Warn",
		9:  "InActiveWarn",
		10: "Ban",
		11: "InActiveBan",
		12: "CreatePromoCode",
		13: "DeletePromoCode",
		14: "ActivatePromoCode",
		15: "AddUsesForPromo",
		16: "AddTimeForPromo",
		17: "DecrementUsesPromo",
		18: "AddActivationPromoCodeToHistory",
		19: "CreateCheck",
		20: "UseCheck",
		21: "DeleteCheck",
	}
	TransactionType_value = map[string]int32{
		"Get":                             0,
		"Set":                             1,
		"Transfer":                        2,
		"Purchase":                        3,
		"Farm":                            4,
		"Block":                           5,
		"User":                            6,
		"Moderator":                       7,
		"Warn":                            8,
		"InActiveWarn":                    9,
		"Ban":                             10,
		"InActiveBan":                     11,
		"CreatePromoCode":                 12,
		"DeletePromoCode":                 13,
		"ActivatePromoCode":               14,
		"AddUsesForPromo":                 15,
		"AddTimeForPromo":                 16,
		"DecrementUsesPromo":              17,
		"AddActivationPromoCodeToHistory": 18,
		"CreateCheck":                     19,
		"UseCheck":                        20,
		"DeleteCheck":                     21,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[1].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[1]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

type ErrorCode int32

const (
	ErrorCode_UserNotFound      ErrorCode = 0
	ErrorCode_NotEnoughMoney    ErrorCode = 1
	ErrorCode_Forbidden         ErrorCode = 2
	ErrorCode_PromoNotValid     ErrorCode = 3
	ErrorCode_CheckNotValid     ErrorCode = 4
	ErrorCode_UserBadRole       ErrorCode = 5
	ErrorCode_UserAlreadyBanned ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UserNotFound",
		1: "NotEnoughMoney",
		2: "Forbidden",
		3: "PromoNotValid",
		4: "CheckNotValid",
		5: "UserBadRole",
		6: "UserAlreadyBanned",
	}
	ErrorCode_value = map[string]int32{
		"UserNotFound":      0,
		"NotEnoughMoney":    1,
		"Forbidden":         2,
		"PromoNotValid":     3,
		"CheckNotValid":     4,
		"UserBadRole":       5,
		"UserAlreadyBanned": 6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{2}
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=common.ErrorCode" json:"code,omitempty"`
	Details       map[string]string      `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *Failure) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_UserNotFound
}

func (x *Failure) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_common_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failure       *Failure               `protobuf:"bytes,1,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_common_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

var File_common_types_proto protoreflect.FileDescriptor

const file_common_types_proto_rawDesc = "" +
	"\n" +
	"\x12common/types.proto\x12\x06common\"\xa4\x01\n" +
	"\aFailure\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.common.ErrorCodeR\x04code\x126\n" +
	"\adetails\x18\x02 \x03(\v2\x1c.common.Failure.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x06\n" +
	"\x04Void\"F\n" +
	"\bResponse\x12.\n" +
	"\afailure\x18\x01 \x01(\v2\x0f.common.FailureH\x00R\afailure\x88\x01\x01B\n" +
	"\n" +
	"\b_failure*5\n" +
	"\bCurrency\x12\x10\n" +
	"\fNoneCurrency\x10\x00\x12\v\n" +
	"\aCredits\x10\x01\x12\n" +
	"\n" +
	"\x06Stocks\x10\x02*\xfb\x02\n" +
	"\x0fTransactionType\x12\a\n" +
	"\x03Get\x10\x00\x12\a\n" +
	"\x03Set\x10\x01\x12\f\n" +
	"\bTransfer\x10\x02\x12\f\n" +
	"\bPurchase\x10\x03\x12\b\n" +
	"\x04Farm\x10\x04\x12\t\n" +
	"\x05Block\x10\x05\x12\b\n" +
	"\x04User\x10\x06\x12\r\n" +
	"\tModerator\x10\a\x12\b\n" +
	"\x04Warn\x10\b\x12\x10\n" +
	"\fInActiveWarn\x10\t\x12\a\n" +
	"\x03Ban\x10\n" +
	"\x12\x0f\n" +
	"\vInActiveBan\x10\v\x12\x13\n" +
	"\x0fCreatePromoCode\x10\f\x12\x13\n" +
	"\x0fDeletePromoCode\x10\r\x12\x15\n" +
	"\x11ActivatePromoCode\x10\x0e\x12\x13\n" +
	"\x0fAddUsesForPromo\x10\x0f\x12\x13\n" +
	"\x0fAddTimeForPromo\x10\x10\x12\x16\n" +
	"\x12DecrementUsesPromo\x10\x11\x12#\n" +
	"\x1fAddActivationPromoCodeToHistory\x10\x12\x12\x0f\n" +
	"\vCreateCheck\x10\x13\x12\f\n" +
	"\bUseCheck\x10\x14\x12\x0f\n" +
	"\vDeleteCheck\x10\x15*\x8e\x01\n" +
	"\tErrorCode\x12\x10\n" +
	"\fUserNotFound\x10\x00\x12\x12\n" +
	"\x0eNotEnoughMoney\x10\x01\x12\r\n" +
	"\tForbidden\x10\x02\x12\x11\n" +
	"\rPromoNotValid\x10\x03\x12\x11\n" +
	"\rCheckNotValid\x10\x04\x12\x0f\n" +
	"\vUserBadRole\x10\x05\x12\x15\n" +
	"\x11UserAlreadyBanned\x10\x06B\n" +
	"Z\b./commonb\x06proto3"

var (
	file_common_types_proto_rawDescOnce sync.Once
	file_common_types_proto_rawDescData []byte
)

func file_common_types_proto_rawDescGZIP() []byte {
	file_common_types_proto_rawDescOnce.Do(func() {
		file_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)))
	})
	return file_common_types_proto_rawDescData
}

var file_common_types_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_types_proto_goTypes = []any{
	(Currency)(0),        // 0: common.Currency
	(TransactionType)(0), // 1: common.TransactionType
	(ErrorCode)(0),       // 2: common.ErrorCode
	(*Failure)(nil),      // 3: common.Failure
	(*Void)(nil),         // 4: common.Void
	(*Response)(nil),     // 5: common.Response
	nil,                  // 6: common.Failure.DetailsEntry
}
var file_common_types_proto_depIdxs = []int32{
	2, // 0: common.Failure.code:type_name -> common.ErrorCode
	6, // 1: common.Failure.details:type_name -> common.Failure.DetailsEntry
	3, // 2: common.Response.failure:type_name -> common.Failure
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_types_proto_init() }
func file_common_types_proto_init() {
	if File_common_types_proto != nil {
		return
	}
	file_common_types_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_proto_goTypes,
		DependencyIndexes: file_common_types_proto_depIdxs,
		EnumInfos:         file_common_types_proto_enumTypes,
		MessageInfos:      file_common_types_proto_msgTypes,
	}.Build()
	File_common_types_proto = out.File
	file_common_types_proto_goTypes = nil
	file_common_types_proto_depIdxs = nil
}
