// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: warns/service.proto

package warns

import (
	common "warns/pkg/models/common"
	users "warns/pkg/models/users"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Warn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ModerId       int64                  `protobuf:"varint,3,opt,name=ModerId,proto3" json:"ModerId,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=Reason,proto3" json:"Reason,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warn) Reset() {
	*x = Warn{}
	mi := &file_warns_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warn) ProtoMessage() {}

func (x *Warn) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warn.ProtoReflect.Descriptor instead.
func (*Warn) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{0}
}

func (x *Warn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warn) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Warn) GetModerId() int64 {
	if x != nil {
		return x.ModerId
	}
	return 0
}

func (x *Warn) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Warn) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Warn) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type Ban struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ModerId       int64                  `protobuf:"varint,3,opt,name=ModerId,proto3" json:"ModerId,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=Reason,proto3" json:"Reason,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ban) Reset() {
	*x = Ban{}
	mi := &file_warns_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ban) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ban) ProtoMessage() {}

func (x *Ban) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ban.ProtoReflect.Descriptor instead.
func (*Ban) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{1}
}

func (x *Ban) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ban) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Ban) GetModerId() int64 {
	if x != nil {
		return x.ModerId
	}
	return 0
}

func (x *Ban) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Ban) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Ban) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ModerId       int64                  `protobuf:"varint,2,opt,name=ModerId,proto3" json:"ModerId,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=Reason,proto3,oneof" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIn) Reset() {
	*x = CreateIn{}
	mi := &file_warns_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIn) ProtoMessage() {}

func (x *CreateIn) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIn.ProtoReflect.Descriptor instead.
func (*CreateIn) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIn) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateIn) GetModerId() int64 {
	if x != nil {
		return x.ModerId
	}
	return 0
}

func (x *CreateIn) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type CreateFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warn          *Warn                  `protobuf:"bytes,1,opt,name=warn,proto3,oneof" json:"warn,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFailure) Reset() {
	*x = CreateFailure{}
	mi := &file_warns_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFailure) ProtoMessage() {}

func (x *CreateFailure) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFailure.ProtoReflect.Descriptor instead.
func (*CreateFailure) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFailure) GetWarn() *Warn {
	if x != nil {
		return x.Warn
	}
	return nil
}

func (x *CreateFailure) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type BanFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ban           *Ban                   `protobuf:"bytes,1,opt,name=ban,proto3,oneof" json:"ban,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanFailure) Reset() {
	*x = BanFailure{}
	mi := &file_warns_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanFailure) ProtoMessage() {}

func (x *BanFailure) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanFailure.ProtoReflect.Descriptor instead.
func (*BanFailure) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{4}
}

func (x *BanFailure) GetBan() *Ban {
	if x != nil {
		return x.Ban
	}
	return nil
}

func (x *BanFailure) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

var File_warns_service_proto protoreflect.FileDescriptor

const file_warns_service_proto_rawDesc = "" +
	"\n" +
	"\x13warns/service.proto\x12\x05warns\x1a\x12common/types.proto\x1a\x13users/service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\x04Warn\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aModerId\x18\x03 \x01(\x03R\aModerId\x12\x16\n" +
	"\x06Reason\x18\x04 \x01(\tR\x06Reason\x126\n" +
	"\bIssuedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bIssuedAt\x12\x1a\n" +
	"\bIsActive\x18\x06 \x01(\bR\bIsActive\"\xb3\x01\n" +
	"\x03Ban\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aModerId\x18\x03 \x01(\x03R\aModerId\x12\x16\n" +
	"\x06Reason\x18\x04 \x01(\tR\x06Reason\x126\n" +
	"\bIssuedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bIssuedAt\x12\x1a\n" +
	"\bIsActive\x18\x06 \x01(\bR\bIsActive\"d\n" +
	"\bCreateIn\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aModerId\x18\x02 \x01(\x03R\aModerId\x12\x1b\n" +
	"\x06Reason\x18\x03 \x01(\tH\x00R\x06Reason\x88\x01\x01B\t\n" +
	"\a_Reason\"z\n" +
	"\rCreateFailure\x12$\n" +
	"\x04warn\x18\x01 \x01(\v2\v.warns.WarnH\x00R\x04warn\x88\x01\x01\x12.\n" +
	"\afailure\x18\x02 \x01(\v2\x0f.common.FailureH\x01R\afailure\x88\x01\x01B\a\n" +
	"\x05_warnB\n" +
	"\n" +
	"\b_failure\"s\n" +
	"\n" +
	"BanFailure\x12!\n" +
	"\x03ban\x18\x01 \x01(\v2\n" +
	".warns.BanH\x00R\x03ban\x88\x01\x01\x12.\n" +
	"\afailure\x18\x02 \x01(\v2\x0f.common.FailureH\x01R\afailure\x88\x01\x01B\x06\n" +
	"\x04_banB\n" +
	"\n" +
	"\b_failure2\x83\x01\n" +
	"\x05Warns\x12/\n" +
	"\x06Create\x12\x0f.warns.CreateIn\x1a\x14.warns.CreateFailure\x12#\n" +
	"\x03Ban\x12\t.users.Id\x1a\x11.warns.BanFailure\x12$\n" +
	"\x05Unban\x12\t.users.Id\x1a\x10.common.ResponseB\tZ\a./warnsb\x06proto3"

var (
	file_warns_service_proto_rawDescOnce sync.Once
	file_warns_service_proto_rawDescData []byte
)

func file_warns_service_proto_rawDescGZIP() []byte {
	file_warns_service_proto_rawDescOnce.Do(func() {
		file_warns_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warns_service_proto_rawDesc), len(file_warns_service_proto_rawDesc)))
	})
	return file_warns_service_proto_rawDescData
}

var file_warns_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_warns_service_proto_goTypes = []any{
	(*Warn)(nil),                  // 0: warns.Warn
	(*Ban)(nil),                   // 1: warns.Ban
	(*CreateIn)(nil),              // 2: warns.CreateIn
	(*CreateFailure)(nil),         // 3: warns.CreateFailure
	(*BanFailure)(nil),            // 4: warns.BanFailure
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*common.Failure)(nil),        // 6: common.Failure
	(*users.Id)(nil),              // 7: users.Id
	(*common.Response)(nil),       // 8: common.Response
}
var file_warns_service_proto_depIdxs = []int32{
	5, // 0: warns.Warn.IssuedAt:type_name -> google.protobuf.Timestamp
	5, // 1: warns.Ban.IssuedAt:type_name -> google.protobuf.Timestamp
	0, // 2: warns.CreateFailure.warn:type_name -> warns.Warn
	6, // 3: warns.CreateFailure.failure:type_name -> common.Failure
	1, // 4: warns.BanFailure.ban:type_name -> warns.Ban
	6, // 5: warns.BanFailure.failure:type_name -> common.Failure
	2, // 6: warns.Warns.Create:input_type -> warns.CreateIn
	7, // 7: warns.Warns.Ban:input_type -> users.Id
	7, // 8: warns.Warns.Unban:input_type -> users.Id
	3, // 9: warns.Warns.Create:output_type -> warns.CreateFailure
	4, // 10: warns.Warns.Ban:output_type -> warns.BanFailure
	8, // 11: warns.Warns.Unban:output_type -> common.Response
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_warns_service_proto_init() }
func file_warns_service_proto_init() {
	if File_warns_service_proto != nil {
		return
	}
	file_warns_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_warns_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_warns_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warns_service_proto_rawDesc), len(file_warns_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warns_service_proto_goTypes,
		DependencyIndexes: file_warns_service_proto_depIdxs,
		MessageInfos:      file_warns_service_proto_msgTypes,
	}.Build()
	File_warns_service_proto = out.File
	file_warns_service_proto_goTypes = nil
	file_warns_service_proto_depIdxs = nil
}
