// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: warns/service.proto

package warns

import (
	common "warns/pkg/models/common"
	users "warns/pkg/models/users"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Warn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ModerId       int64                  `protobuf:"varint,3,opt,name=ModerId,proto3" json:"ModerId,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=Reason,proto3" json:"Reason,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warn) Reset() {
	*x = Warn{}
	mi := &file_warns_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warn) ProtoMessage() {}

func (x *Warn) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warn.ProtoReflect.Descriptor instead.
func (*Warn) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{0}
}

func (x *Warn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Warn) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Warn) GetModerId() int64 {
	if x != nil {
		return x.ModerId
	}
	return 0
}

func (x *Warn) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Warn) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Warn) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type WarnFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warn          *Warn                  `protobuf:"bytes,1,opt,name=warn,proto3,oneof" json:"warn,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarnFailure) Reset() {
	*x = WarnFailure{}
	mi := &file_warns_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarnFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarnFailure) ProtoMessage() {}

func (x *WarnFailure) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarnFailure.ProtoReflect.Descriptor instead.
func (*WarnFailure) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{1}
}

func (x *WarnFailure) GetWarn() *Warn {
	if x != nil {
		return x.Warn
	}
	return nil
}

func (x *WarnFailure) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type AllWarns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warns         []*Warn                `protobuf:"bytes,1,rep,name=warns,proto3" json:"warns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllWarns) Reset() {
	*x = AllWarns{}
	mi := &file_warns_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllWarns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllWarns) ProtoMessage() {}

func (x *AllWarns) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllWarns.ProtoReflect.Descriptor instead.
func (*AllWarns) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{2}
}

func (x *AllWarns) GetWarns() []*Warn {
	if x != nil {
		return x.Warns
	}
	return nil
}

type AllWarnsFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warns         *AllWarns              `protobuf:"bytes,1,opt,name=warns,proto3,oneof" json:"warns,omitempty"`
	Failure       *common.Response       `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllWarnsFailure) Reset() {
	*x = AllWarnsFailure{}
	mi := &file_warns_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllWarnsFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllWarnsFailure) ProtoMessage() {}

func (x *AllWarnsFailure) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllWarnsFailure.ProtoReflect.Descriptor instead.
func (*AllWarnsFailure) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{3}
}

func (x *AllWarnsFailure) GetWarns() *AllWarns {
	if x != nil {
		return x.Warns
	}
	return nil
}

func (x *AllWarnsFailure) GetFailure() *common.Response {
	if x != nil {
		return x.Failure
	}
	return nil
}

type WarnCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ModerId       int64                  `protobuf:"varint,2,opt,name=ModerId,proto3" json:"ModerId,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=Reason,proto3,oneof" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarnCreate) Reset() {
	*x = WarnCreate{}
	mi := &file_warns_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarnCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarnCreate) ProtoMessage() {}

func (x *WarnCreate) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarnCreate.ProtoReflect.Descriptor instead.
func (*WarnCreate) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{4}
}

func (x *WarnCreate) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WarnCreate) GetModerId() int64 {
	if x != nil {
		return x.ModerId
	}
	return 0
}

func (x *WarnCreate) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type Ban struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ModerId       int64                  `protobuf:"varint,3,opt,name=ModerId,proto3" json:"ModerId,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=Reason,proto3" json:"Reason,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ban) Reset() {
	*x = Ban{}
	mi := &file_warns_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ban) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ban) ProtoMessage() {}

func (x *Ban) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ban.ProtoReflect.Descriptor instead.
func (*Ban) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{5}
}

func (x *Ban) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ban) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Ban) GetModerId() int64 {
	if x != nil {
		return x.ModerId
	}
	return 0
}

func (x *Ban) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Ban) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Ban) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type BanFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ban           *Ban                   `protobuf:"bytes,1,opt,name=ban,proto3,oneof" json:"ban,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanFailure) Reset() {
	*x = BanFailure{}
	mi := &file_warns_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanFailure) ProtoMessage() {}

func (x *BanFailure) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanFailure.ProtoReflect.Descriptor instead.
func (*BanFailure) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{6}
}

func (x *BanFailure) GetBan() *Ban {
	if x != nil {
		return x.Ban
	}
	return nil
}

func (x *BanFailure) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type AllBans struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bans          []*Ban                 `protobuf:"bytes,1,rep,name=bans,proto3" json:"bans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllBans) Reset() {
	*x = AllBans{}
	mi := &file_warns_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllBans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllBans) ProtoMessage() {}

func (x *AllBans) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllBans.ProtoReflect.Descriptor instead.
func (*AllBans) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{7}
}

func (x *AllBans) GetBans() []*Ban {
	if x != nil {
		return x.Bans
	}
	return nil
}

type AllBansFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bans          *AllBans               `protobuf:"bytes,1,opt,name=bans,proto3,oneof" json:"bans,omitempty"`
	Failure       *common.Response       `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllBansFailure) Reset() {
	*x = AllBansFailure{}
	mi := &file_warns_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllBansFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllBansFailure) ProtoMessage() {}

func (x *AllBansFailure) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllBansFailure.ProtoReflect.Descriptor instead.
func (*AllBansFailure) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{8}
}

func (x *AllBansFailure) GetBans() *AllBans {
	if x != nil {
		return x.Bans
	}
	return nil
}

func (x *AllBansFailure) GetFailure() *common.Response {
	if x != nil {
		return x.Failure
	}
	return nil
}

type BanCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ModerId       int64                  `protobuf:"varint,2,opt,name=ModerId,proto3" json:"ModerId,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=Reason,proto3,oneof" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanCreate) Reset() {
	*x = BanCreate{}
	mi := &file_warns_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanCreate) ProtoMessage() {}

func (x *BanCreate) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanCreate.ProtoReflect.Descriptor instead.
func (*BanCreate) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{9}
}

func (x *BanCreate) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BanCreate) GetModerId() int64 {
	if x != nil {
		return x.ModerId
	}
	return 0
}

func (x *BanCreate) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type CountOfActiveWarns struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountWarns    int32                  `protobuf:"varint,1,opt,name=countWarns,proto3" json:"countWarns,omitempty"`
	Failure       *common.Response       `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountOfActiveWarns) Reset() {
	*x = CountOfActiveWarns{}
	mi := &file_warns_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountOfActiveWarns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountOfActiveWarns) ProtoMessage() {}

func (x *CountOfActiveWarns) ProtoReflect() protoreflect.Message {
	mi := &file_warns_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountOfActiveWarns.ProtoReflect.Descriptor instead.
func (*CountOfActiveWarns) Descriptor() ([]byte, []int) {
	return file_warns_service_proto_rawDescGZIP(), []int{10}
}

func (x *CountOfActiveWarns) GetCountWarns() int32 {
	if x != nil {
		return x.CountWarns
	}
	return 0
}

func (x *CountOfActiveWarns) GetFailure() *common.Response {
	if x != nil {
		return x.Failure
	}
	return nil
}

var File_warns_service_proto protoreflect.FileDescriptor

const file_warns_service_proto_rawDesc = "" +
	"\n" +
	"\x13warns/service.proto\x12\x05warns\x1a\x12common/types.proto\x1a\x13users/service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n" +
	"\x04Warn\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aModerId\x18\x03 \x01(\x03R\aModerId\x12\x16\n" +
	"\x06Reason\x18\x04 \x01(\tR\x06Reason\x126\n" +
	"\bIssuedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bIssuedAt\x12\x1a\n" +
	"\bIsActive\x18\x06 \x01(\bR\bIsActive\"x\n" +
	"\vWarnFailure\x12$\n" +
	"\x04warn\x18\x01 \x01(\v2\v.warns.WarnH\x00R\x04warn\x88\x01\x01\x12.\n" +
	"\afailure\x18\x02 \x01(\v2\x0f.common.FailureH\x01R\afailure\x88\x01\x01B\a\n" +
	"\x05_warnB\n" +
	"\n" +
	"\b_failure\"-\n" +
	"\bAllWarns\x12!\n" +
	"\x05warns\x18\x01 \x03(\v2\v.warns.WarnR\x05warns\"\x84\x01\n" +
	"\x0fAllWarnsFailure\x12*\n" +
	"\x05warns\x18\x01 \x01(\v2\x0f.warns.AllWarnsH\x00R\x05warns\x88\x01\x01\x12/\n" +
	"\afailure\x18\x02 \x01(\v2\x10.common.ResponseH\x01R\afailure\x88\x01\x01B\b\n" +
	"\x06_warnsB\n" +
	"\n" +
	"\b_failure\"f\n" +
	"\n" +
	"WarnCreate\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aModerId\x18\x02 \x01(\x03R\aModerId\x12\x1b\n" +
	"\x06Reason\x18\x03 \x01(\tH\x00R\x06Reason\x88\x01\x01B\t\n" +
	"\a_Reason\"\xb3\x01\n" +
	"\x03Ban\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aModerId\x18\x03 \x01(\x03R\aModerId\x12\x16\n" +
	"\x06Reason\x18\x04 \x01(\tR\x06Reason\x126\n" +
	"\bIssuedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bIssuedAt\x12\x1a\n" +
	"\bIsActive\x18\x06 \x01(\bR\bIsActive\"s\n" +
	"\n" +
	"BanFailure\x12!\n" +
	"\x03ban\x18\x01 \x01(\v2\n" +
	".warns.BanH\x00R\x03ban\x88\x01\x01\x12.\n" +
	"\afailure\x18\x02 \x01(\v2\x0f.common.FailureH\x01R\afailure\x88\x01\x01B\x06\n" +
	"\x04_banB\n" +
	"\n" +
	"\b_failure\")\n" +
	"\aAllBans\x12\x1e\n" +
	"\x04bans\x18\x01 \x03(\v2\n" +
	".warns.BanR\x04bans\"\x7f\n" +
	"\x0eAllBansFailure\x12'\n" +
	"\x04bans\x18\x01 \x01(\v2\x0e.warns.AllBansH\x00R\x04bans\x88\x01\x01\x12/\n" +
	"\afailure\x18\x02 \x01(\v2\x10.common.ResponseH\x01R\afailure\x88\x01\x01B\a\n" +
	"\x05_bansB\n" +
	"\n" +
	"\b_failure\"e\n" +
	"\tBanCreate\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aModerId\x18\x02 \x01(\x03R\aModerId\x12\x1b\n" +
	"\x06Reason\x18\x03 \x01(\tH\x00R\x06Reason\x88\x01\x01B\t\n" +
	"\a_Reason\"q\n" +
	"\x12CountOfActiveWarns\x12\x1e\n" +
	"\n" +
	"countWarns\x18\x01 \x01(\x05R\n" +
	"countWarns\x12/\n" +
	"\afailure\x18\x02 \x01(\v2\x10.common.ResponseH\x00R\afailure\x88\x01\x01B\n" +
	"\n" +
	"\b_failure2\xe9\x03\n" +
	"\x05Warns\x12-\n" +
	"\x04Warn\x12\x11.warns.WarnCreate\x1a\x12.warns.WarnFailure\x12(\n" +
	"\tAllUnWarn\x12\t.users.Id\x1a\x10.common.Response\x12)\n" +
	"\n" +
	"LastUnWarn\x12\t.users.Id\x1a\x10.common.Response\x12*\n" +
	"\x03Ban\x12\x10.warns.BanCreate\x1a\x11.warns.BanFailure\x12$\n" +
	"\x05Unban\x12\t.users.Id\x1a\x10.common.Response\x124\n" +
	"\x0fGetHistoryWarns\x12\t.users.Id\x1a\x16.warns.AllWarnsFailure\x122\n" +
	"\x0eGetHistoryBans\x12\t.users.Id\x1a\x15.warns.AllBansFailure\x123\n" +
	"\x0eGetActiveWarns\x12\t.users.Id\x1a\x16.warns.AllWarnsFailure\x12,\n" +
	"\fGetActiveBan\x12\t.users.Id\x1a\x11.warns.BanFailure\x12=\n" +
	"\x15GetCountOfActiveWarns\x12\t.users.Id\x1a\x19.warns.CountOfActiveWarnsB\tZ\a./warnsb\x06proto3"

var (
	file_warns_service_proto_rawDescOnce sync.Once
	file_warns_service_proto_rawDescData []byte
)

func file_warns_service_proto_rawDescGZIP() []byte {
	file_warns_service_proto_rawDescOnce.Do(func() {
		file_warns_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warns_service_proto_rawDesc), len(file_warns_service_proto_rawDesc)))
	})
	return file_warns_service_proto_rawDescData
}

var file_warns_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_warns_service_proto_goTypes = []any{
	(*Warn)(nil),                  // 0: warns.Warn
	(*WarnFailure)(nil),           // 1: warns.WarnFailure
	(*AllWarns)(nil),              // 2: warns.AllWarns
	(*AllWarnsFailure)(nil),       // 3: warns.AllWarnsFailure
	(*WarnCreate)(nil),            // 4: warns.WarnCreate
	(*Ban)(nil),                   // 5: warns.Ban
	(*BanFailure)(nil),            // 6: warns.BanFailure
	(*AllBans)(nil),               // 7: warns.AllBans
	(*AllBansFailure)(nil),        // 8: warns.AllBansFailure
	(*BanCreate)(nil),             // 9: warns.BanCreate
	(*CountOfActiveWarns)(nil),    // 10: warns.CountOfActiveWarns
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*common.Failure)(nil),        // 12: common.Failure
	(*common.Response)(nil),       // 13: common.Response
	(*users.Id)(nil),              // 14: users.Id
}
var file_warns_service_proto_depIdxs = []int32{
	11, // 0: warns.Warn.IssuedAt:type_name -> google.protobuf.Timestamp
	0,  // 1: warns.WarnFailure.warn:type_name -> warns.Warn
	12, // 2: warns.WarnFailure.failure:type_name -> common.Failure
	0,  // 3: warns.AllWarns.warns:type_name -> warns.Warn
	2,  // 4: warns.AllWarnsFailure.warns:type_name -> warns.AllWarns
	13, // 5: warns.AllWarnsFailure.failure:type_name -> common.Response
	11, // 6: warns.Ban.IssuedAt:type_name -> google.protobuf.Timestamp
	5,  // 7: warns.BanFailure.ban:type_name -> warns.Ban
	12, // 8: warns.BanFailure.failure:type_name -> common.Failure
	5,  // 9: warns.AllBans.bans:type_name -> warns.Ban
	7,  // 10: warns.AllBansFailure.bans:type_name -> warns.AllBans
	13, // 11: warns.AllBansFailure.failure:type_name -> common.Response
	13, // 12: warns.CountOfActiveWarns.failure:type_name -> common.Response
	4,  // 13: warns.Warns.Warn:input_type -> warns.WarnCreate
	14, // 14: warns.Warns.AllUnWarn:input_type -> users.Id
	14, // 15: warns.Warns.LastUnWarn:input_type -> users.Id
	9,  // 16: warns.Warns.Ban:input_type -> warns.BanCreate
	14, // 17: warns.Warns.Unban:input_type -> users.Id
	14, // 18: warns.Warns.GetHistoryWarns:input_type -> users.Id
	14, // 19: warns.Warns.GetHistoryBans:input_type -> users.Id
	14, // 20: warns.Warns.GetActiveWarns:input_type -> users.Id
	14, // 21: warns.Warns.GetActiveBan:input_type -> users.Id
	14, // 22: warns.Warns.GetCountOfActiveWarns:input_type -> users.Id
	1,  // 23: warns.Warns.Warn:output_type -> warns.WarnFailure
	13, // 24: warns.Warns.AllUnWarn:output_type -> common.Response
	13, // 25: warns.Warns.LastUnWarn:output_type -> common.Response
	6,  // 26: warns.Warns.Ban:output_type -> warns.BanFailure
	13, // 27: warns.Warns.Unban:output_type -> common.Response
	3,  // 28: warns.Warns.GetHistoryWarns:output_type -> warns.AllWarnsFailure
	8,  // 29: warns.Warns.GetHistoryBans:output_type -> warns.AllBansFailure
	3,  // 30: warns.Warns.GetActiveWarns:output_type -> warns.AllWarnsFailure
	6,  // 31: warns.Warns.GetActiveBan:output_type -> warns.BanFailure
	10, // 32: warns.Warns.GetCountOfActiveWarns:output_type -> warns.CountOfActiveWarns
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_warns_service_proto_init() }
func file_warns_service_proto_init() {
	if File_warns_service_proto != nil {
		return
	}
	file_warns_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_warns_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_warns_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_warns_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_warns_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_warns_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_warns_service_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warns_service_proto_rawDesc), len(file_warns_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warns_service_proto_goTypes,
		DependencyIndexes: file_warns_service_proto_depIdxs,
		MessageInfos:      file_warns_service_proto_msgTypes,
	}.Build()
	File_warns_service_proto = out.File
	file_warns_service_proto_goTypes = nil
	file_warns_service_proto_depIdxs = nil
}
