-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS Promos  (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Currency SMALLINT,
    Amount INT NOT NULL,
    Uses INT NOT NULL,
    Creator BIGINT REFERENCES Users(Id),
    ExpAt TIMESTAMP NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS Promos;
-- +goose StatementEnd

