-- +goose Up
-- +goose StatementBegin
CREATE TABLE Users (
    Id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Credits bigint NOT NULL,
    Stocks bigint NOT NULL,
    PremiumCredits bigint NOT NULL,
    Role integer NOT NULL,
    AutoBuyEnabled boolean NOT NULL,
    LastFarmingAt timestamp with time zone NOT NULL,
    CreatedAt timestamp with time zone NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS Users;
-- +goose StatementEnd
