-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS Warns  (
    Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId BIGINT REFERENCES Users(Id),
    ModetatorId BIGINT REFERENCES Users(Id),
    Reason TEXT,
    IssuedAt TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    IsActive BOOLEAN DEFAULT TRUE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS Warns;
-- +goose StatementEnd
