package errorsd

import (
	"errors"
)

var (
	ErrExecQuery             = errors.New("error exeсution query")
	ErrTransactionCommit     = errors.New("error transaction commit")
	ErrTransactionRollback   = errors.New("error transaction rollback")
	ErrMissingEnviroment     = errors.New("error missing enviroment")
	ErrWrongUserId           = errors.New("error wrong user id")
	ErrIncorrectData         = errors.New("error cannot scan data")
	ErrServiceUsers          = errors.New("error on service users")
	ErrDoWithTries           = errors.New("error after %d attemps got fail")
	ErrWrongTypeData         = errors.New("error not supported type data")
	ErrSendTransaction       = errors.New("error send transaction to service users")
	ErrCheckNotValid         = errors.New("check key invalid or missing")
	ErrBadArgs               = errors.New("error bad args: 0 <= Currency <= 2 AND Amount >= 0 AND (Uses > 0 OR Uses = -1)")
	ErrExpAt                 = errors.New("error timestamb of expired data must be more then now")
	ErrCreatorIsNotOwner     = errors.New("error creator of promo must be have role owner")
	ErrValueUses             = errors.New("error value of uses must be > 0, for infinity uses set -1")
	ErrUniquePromo           = errors.New("error name of promo must be unique")
	ErrMissingPromoId        = errors.New("error missing promo id")
	ErrMissingPromoName      = errors.New("error missing promo name")
	ErrPromoExpired          = errors.New("error promocode expired")
	ErrPromoNotInStock       = errors.New("error promocode activations are over")
	ErrPromoAlreadyActivated = errors.New("error promo is already activated by user")
	ErrUserIsNotModerator    = errors.New("error only moderators can give warns")
	ErrCreateWarn            = errors.New("error create warn")
	ErrCreateBan             = errors.New("error create ban")
	ErrGetWarns              = errors.New("error get warns")
	ErrGetBans               = errors.New("error get bans")
	ErrMakeWarnsInActive     = errors.New("error make warns inactive")
	ErrMakeBansInActive      = errors.New("error make bans inactive")
	ErrCountActiveWarns      = errors.New("error get count of active warns")
	ErrUserAlreadyBanned     = errors.New("error user already banned")
)
