// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: market/service.proto

package market

import (
	common "protobuf/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_Command Type = 0
	Type_Pack    Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "Command",
		1: "Pack",
	}
	Type_value = map[string]int32{
		"Command": 0,
		"Pack":    1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_market_service_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_market_service_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{0}
}

type SortingMethod int32

const (
	SortingMethod_Asc  SortingMethod = 0
	SortingMethod_Desc SortingMethod = 1
)

// Enum value maps for SortingMethod.
var (
	SortingMethod_name = map[int32]string{
		0: "Asc",
		1: "Desc",
	}
	SortingMethod_value = map[string]int32{
		"Asc":  0,
		"Desc": 1,
	}
)

func (x SortingMethod) Enum() *SortingMethod {
	p := new(SortingMethod)
	*p = x
	return p
}

func (x SortingMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortingMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_market_service_proto_enumTypes[1].Descriptor()
}

func (SortingMethod) Type() protoreflect.EnumType {
	return &file_market_service_proto_enumTypes[1]
}

func (x SortingMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortingMethod.Descriptor instead.
func (SortingMethod) EnumDescriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{1}
}

type SortingBy int32

const (
	SortingBy_recent SortingBy = 0
	SortingBy_cost   SortingBy = 1
	SortingBy_type   SortingBy = 2
)

// Enum value maps for SortingBy.
var (
	SortingBy_name = map[int32]string{
		0: "recent",
		1: "cost",
		2: "type",
	}
	SortingBy_value = map[string]int32{
		"recent": 0,
		"cost":   1,
		"type":   2,
	}
)

func (x SortingBy) Enum() *SortingBy {
	p := new(SortingBy)
	*p = x
	return p
}

func (x SortingBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortingBy) Descriptor() protoreflect.EnumDescriptor {
	return file_market_service_proto_enumTypes[2].Descriptor()
}

func (SortingBy) Type() protoreflect.EnumType {
	return &file_market_service_proto_enumTypes[2]
}

func (x SortingBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortingBy.Descriptor instead.
func (SortingBy) EnumDescriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{2}
}

type TypeName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Type                   `protobuf:"varint,1,opt,name=type,proto3,enum=market.Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeName) Reset() {
	*x = TypeName{}
	mi := &file_market_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeName) ProtoMessage() {}

func (x *TypeName) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeName.ProtoReflect.Descriptor instead.
func (*TypeName) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{0}
}

func (x *TypeName) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Command
}

func (x *TypeName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=market.Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Seller        int64                  `protobuf:"varint,4,opt,name=seller,proto3" json:"seller,omitempty"`
	Cost          int64                  `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	UpForSaleAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=upForSaleAt,proto3" json:"upForSaleAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_market_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{1}
}

func (x *Offer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Offer) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Command
}

func (x *Offer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Offer) GetSeller() int64 {
	if x != nil {
		return x.Seller
	}
	return 0
}

func (x *Offer) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Offer) GetUpForSaleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpForSaleAt
	}
	return nil
}

type OfferCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Type                   `protobuf:"varint,1,opt,name=type,proto3,enum=market.Type" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cost          int64                  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Seller        int64                  `protobuf:"varint,4,opt,name=seller,proto3" json:"seller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferCreate) Reset() {
	*x = OfferCreate{}
	mi := &file_market_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferCreate) ProtoMessage() {}

func (x *OfferCreate) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferCreate.ProtoReflect.Descriptor instead.
func (*OfferCreate) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{2}
}

func (x *OfferCreate) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Command
}

func (x *OfferCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OfferCreate) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *OfferCreate) GetSeller() int64 {
	if x != nil {
		return x.Seller
	}
	return 0
}

type Offers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offers) Reset() {
	*x = Offers{}
	mi := &file_market_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offers) ProtoMessage() {}

func (x *Offers) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offers.ProtoReflect.Descriptor instead.
func (*Offers) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{3}
}

func (x *Offers) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type OfferFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *Offer                 `protobuf:"bytes,1,opt,name=offer,proto3,oneof" json:"offer,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferFailure) Reset() {
	*x = OfferFailure{}
	mi := &file_market_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferFailure) ProtoMessage() {}

func (x *OfferFailure) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferFailure.ProtoReflect.Descriptor instead.
func (*OfferFailure) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{4}
}

func (x *OfferFailure) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *OfferFailure) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type OffersFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        *Offers                `protobuf:"bytes,1,opt,name=offers,proto3,oneof" json:"offers,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffersFailure) Reset() {
	*x = OffersFailure{}
	mi := &file_market_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffersFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffersFailure) ProtoMessage() {}

func (x *OffersFailure) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffersFailure.ProtoReflect.Descriptor instead.
func (*OffersFailure) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{5}
}

func (x *OffersFailure) GetOffers() *Offers {
	if x != nil {
		return x.Offers
	}
	return nil
}

func (x *OffersFailure) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type OffersSorting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        SortingMethod          `protobuf:"varint,1,opt,name=method,proto3,enum=market.SortingMethod" json:"method,omitempty"`
	By            SortingBy              `protobuf:"varint,2,opt,name=by,proto3,enum=market.SortingBy" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffersSorting) Reset() {
	*x = OffersSorting{}
	mi := &file_market_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffersSorting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffersSorting) ProtoMessage() {}

func (x *OffersSorting) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffersSorting.ProtoReflect.Descriptor instead.
func (*OffersSorting) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{6}
}

func (x *OffersSorting) GetMethod() SortingMethod {
	if x != nil {
		return x.Method
	}
	return SortingMethod_Asc
}

func (x *OffersSorting) GetBy() SortingBy {
	if x != nil {
		return x.By
	}
	return SortingBy_recent
}

var File_market_service_proto protoreflect.FileDescriptor

const file_market_service_proto_rawDesc = "" +
	"\n" +
	"\x14market/service.proto\x12\x06market\x1a\x12common/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\bTypeName\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.market.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb7\x01\n" +
	"\x05Offer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x04type\x18\x02 \x01(\x0e2\f.market.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06seller\x18\x04 \x01(\x03R\x06seller\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x03R\x04cost\x12<\n" +
	"\vupForSaleAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vupForSaleAt\"o\n" +
	"\vOfferCreate\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.market.TypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x03R\x04cost\x12\x16\n" +
	"\x06seller\x18\x04 \x01(\x03R\x06seller\"/\n" +
	"\x06Offers\x12%\n" +
	"\x06offers\x18\x01 \x03(\v2\r.market.OfferR\x06offers\"~\n" +
	"\fOfferFailure\x12(\n" +
	"\x05offer\x18\x01 \x01(\v2\r.market.OfferH\x00R\x05offer\x88\x01\x01\x12.\n" +
	"\afailure\x18\x02 \x01(\v2\x0f.common.FailureH\x01R\afailure\x88\x01\x01B\b\n" +
	"\x06_offerB\n" +
	"\n" +
	"\b_failure\"\x83\x01\n" +
	"\rOffersFailure\x12+\n" +
	"\x06offers\x18\x01 \x01(\v2\x0e.market.OffersH\x00R\x06offers\x88\x01\x01\x12.\n" +
	"\afailure\x18\x02 \x01(\v2\x0f.common.FailureH\x01R\afailure\x88\x01\x01B\t\n" +
	"\a_offersB\n" +
	"\n" +
	"\b_failure\"a\n" +
	"\rOffersSorting\x12-\n" +
	"\x06method\x18\x01 \x01(\x0e2\x15.market.SortingMethodR\x06method\x12!\n" +
	"\x02by\x18\x02 \x01(\x0e2\x11.market.SortingByR\x02by*\x1d\n" +
	"\x04Type\x12\v\n" +
	"\aCommand\x10\x00\x12\b\n" +
	"\x04Pack\x10\x01*\"\n" +
	"\rSortingMethod\x12\a\n" +
	"\x03Asc\x10\x00\x12\b\n" +
	"\x04Desc\x10\x01*+\n" +
	"\tSortingBy\x12\n" +
	"\n" +
	"\x06recent\x10\x00\x12\b\n" +
	"\x04cost\x10\x01\x12\b\n" +
	"\x04type\x10\x022\xd3\x01\n" +
	"\x06Market\x12-\n" +
	"\x04Sell\x12\x13.market.OfferCreate\x1a\x10.common.Response\x12)\n" +
	"\x03Buy\x12\x10.market.TypeName\x1a\x10.common.Response\x129\n" +
	"\tGetOffers\x12\x15.market.OffersSorting\x1a\x15.market.OffersFailure\x124\n" +
	"\x0eRemoveFromSell\x12\x10.market.TypeName\x1a\x10.common.ResponseB\n" +
	"Z\b./marketb\x06proto3"

var (
	file_market_service_proto_rawDescOnce sync.Once
	file_market_service_proto_rawDescData []byte
)

func file_market_service_proto_rawDescGZIP() []byte {
	file_market_service_proto_rawDescOnce.Do(func() {
		file_market_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_service_proto_rawDesc), len(file_market_service_proto_rawDesc)))
	})
	return file_market_service_proto_rawDescData
}

var file_market_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_market_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_market_service_proto_goTypes = []any{
	(Type)(0),                     // 0: market.Type
	(SortingMethod)(0),            // 1: market.SortingMethod
	(SortingBy)(0),                // 2: market.SortingBy
	(*TypeName)(nil),              // 3: market.TypeName
	(*Offer)(nil),                 // 4: market.Offer
	(*OfferCreate)(nil),           // 5: market.OfferCreate
	(*Offers)(nil),                // 6: market.Offers
	(*OfferFailure)(nil),          // 7: market.OfferFailure
	(*OffersFailure)(nil),         // 8: market.OffersFailure
	(*OffersSorting)(nil),         // 9: market.OffersSorting
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*common.Failure)(nil),        // 11: common.Failure
	(*common.Response)(nil),       // 12: common.Response
}
var file_market_service_proto_depIdxs = []int32{
	0,  // 0: market.TypeName.type:type_name -> market.Type
	0,  // 1: market.Offer.type:type_name -> market.Type
	10, // 2: market.Offer.upForSaleAt:type_name -> google.protobuf.Timestamp
	0,  // 3: market.OfferCreate.type:type_name -> market.Type
	4,  // 4: market.Offers.offers:type_name -> market.Offer
	4,  // 5: market.OfferFailure.offer:type_name -> market.Offer
	11, // 6: market.OfferFailure.failure:type_name -> common.Failure
	6,  // 7: market.OffersFailure.offers:type_name -> market.Offers
	11, // 8: market.OffersFailure.failure:type_name -> common.Failure
	1,  // 9: market.OffersSorting.method:type_name -> market.SortingMethod
	2,  // 10: market.OffersSorting.by:type_name -> market.SortingBy
	5,  // 11: market.Market.Sell:input_type -> market.OfferCreate
	3,  // 12: market.Market.Buy:input_type -> market.TypeName
	9,  // 13: market.Market.GetOffers:input_type -> market.OffersSorting
	3,  // 14: market.Market.RemoveFromSell:input_type -> market.TypeName
	12, // 15: market.Market.Sell:output_type -> common.Response
	12, // 16: market.Market.Buy:output_type -> common.Response
	8,  // 17: market.Market.GetOffers:output_type -> market.OffersFailure
	12, // 18: market.Market.RemoveFromSell:output_type -> common.Response
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_market_service_proto_init() }
func file_market_service_proto_init() {
	if File_market_service_proto != nil {
		return
	}
	file_market_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_market_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_service_proto_rawDesc), len(file_market_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_service_proto_goTypes,
		DependencyIndexes: file_market_service_proto_depIdxs,
		EnumInfos:         file_market_service_proto_enumTypes,
		MessageInfos:      file_market_service_proto_msgTypes,
	}.Build()
	File_market_service_proto = out.File
	file_market_service_proto_goTypes = nil
	file_market_service_proto_depIdxs = nil
}
