// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: checks/service.proto

package checks

import (
	common "protobuf/common"
	users "protobuf/users"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Currency      common.Currency        `protobuf:"varint,3,opt,name=currency,proto3,enum=common.Currency" json:"currency,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Creator       int64                  `protobuf:"varint,5,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_checks_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_checks_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_checks_service_proto_rawDescGZIP(), []int{0}
}

func (x *Check) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Check) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Check) GetCurrency() common.Currency {
	if x != nil {
		return x.Currency
	}
	return common.Currency(0)
}

func (x *Check) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Check) GetCreator() int64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *Check) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CheckFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         *Check                 `protobuf:"bytes,1,opt,name=check,proto3,oneof" json:"check,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFailure) Reset() {
	*x = CheckFailure{}
	mi := &file_checks_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFailure) ProtoMessage() {}

func (x *CheckFailure) ProtoReflect() protoreflect.Message {
	mi := &file_checks_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFailure.ProtoReflect.Descriptor instead.
func (*CheckFailure) Descriptor() ([]byte, []int) {
	return file_checks_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckFailure) GetCheck() *Check {
	if x != nil {
		return x.Check
	}
	return nil
}

func (x *CheckFailure) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type AllChecks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*Check               `protobuf:"bytes,1,rep,name=Checks,proto3" json:"Checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllChecks) Reset() {
	*x = AllChecks{}
	mi := &file_checks_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllChecks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllChecks) ProtoMessage() {}

func (x *AllChecks) ProtoReflect() protoreflect.Message {
	mi := &file_checks_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllChecks.ProtoReflect.Descriptor instead.
func (*AllChecks) Descriptor() ([]byte, []int) {
	return file_checks_service_proto_rawDescGZIP(), []int{2}
}

func (x *AllChecks) GetChecks() []*Check {
	if x != nil {
		return x.Checks
	}
	return nil
}

type AllChecksFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllChecks     *AllChecks             `protobuf:"bytes,1,opt,name=allChecks,proto3,oneof" json:"allChecks,omitempty"`
	Failure       *common.Failure        `protobuf:"bytes,2,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllChecksFailure) Reset() {
	*x = AllChecksFailure{}
	mi := &file_checks_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllChecksFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllChecksFailure) ProtoMessage() {}

func (x *AllChecksFailure) ProtoReflect() protoreflect.Message {
	mi := &file_checks_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllChecksFailure.ProtoReflect.Descriptor instead.
func (*AllChecksFailure) Descriptor() ([]byte, []int) {
	return file_checks_service_proto_rawDescGZIP(), []int{3}
}

func (x *AllChecksFailure) GetAllChecks() *AllChecks {
	if x != nil {
		return x.AllChecks
	}
	return nil
}

func (x *AllChecksFailure) GetFailure() *common.Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type CheckCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       int64                  `protobuf:"varint,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Currency      common.Currency        `protobuf:"varint,2,opt,name=currency,proto3,enum=common.Currency" json:"currency,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCreate) Reset() {
	*x = CheckCreate{}
	mi := &file_checks_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCreate) ProtoMessage() {}

func (x *CheckCreate) ProtoReflect() protoreflect.Message {
	mi := &file_checks_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCreate.ProtoReflect.Descriptor instead.
func (*CheckCreate) Descriptor() ([]byte, []int) {
	return file_checks_service_proto_rawDescGZIP(), []int{4}
}

func (x *CheckCreate) GetCreator() int64 {
	if x != nil {
		return x.Creator
	}
	return 0
}

func (x *CheckCreate) GetCurrency() common.Currency {
	if x != nil {
		return x.Currency
	}
	return common.Currency(0)
}

func (x *CheckCreate) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CheckUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUse) Reset() {
	*x = CheckUse{}
	mi := &file_checks_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUse) ProtoMessage() {}

func (x *CheckUse) ProtoReflect() protoreflect.Message {
	mi := &file_checks_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUse.ProtoReflect.Descriptor instead.
func (*CheckUse) Descriptor() ([]byte, []int) {
	return file_checks_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckUse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CheckId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckId) Reset() {
	*x = CheckId{}
	mi := &file_checks_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckId) ProtoMessage() {}

func (x *CheckId) ProtoReflect() protoreflect.Message {
	mi := &file_checks_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckId.ProtoReflect.Descriptor instead.
func (*CheckId) Descriptor() ([]byte, []int) {
	return file_checks_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_checks_service_proto protoreflect.FileDescriptor

const file_checks_service_proto_rawDesc = "" +
	"\n" +
	"\x14checks/service.proto\x12\x06checks\x1a\x12common/types.proto\x1a\x13users/service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\x05Check\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12,\n" +
	"\bcurrency\x18\x03 \x01(\x0e2\x10.common.CurrencyR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x18\n" +
	"\acreator\x18\x05 \x01(\x03R\acreator\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"~\n" +
	"\fCheckFailure\x12(\n" +
	"\x05check\x18\x01 \x01(\v2\r.checks.CheckH\x00R\x05check\x88\x01\x01\x12.\n" +
	"\afailure\x18\x02 \x01(\v2\x0f.common.FailureH\x01R\afailure\x88\x01\x01B\b\n" +
	"\x06_checkB\n" +
	"\n" +
	"\b_failure\"2\n" +
	"\tAllChecks\x12%\n" +
	"\x06Checks\x18\x01 \x03(\v2\r.checks.CheckR\x06Checks\"\x92\x01\n" +
	"\x10AllChecksFailure\x124\n" +
	"\tallChecks\x18\x01 \x01(\v2\x11.checks.AllChecksH\x00R\tallChecks\x88\x01\x01\x12.\n" +
	"\afailure\x18\x02 \x01(\v2\x0f.common.FailureH\x01R\afailure\x88\x01\x01B\f\n" +
	"\n" +
	"_allChecksB\n" +
	"\n" +
	"\b_failure\"m\n" +
	"\vCheckCreate\x12\x18\n" +
	"\acreator\x18\x01 \x01(\x03R\acreator\x12,\n" +
	"\bcurrency\x18\x02 \x01(\x0e2\x10.common.CurrencyR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"4\n" +
	"\bCheckUse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x19\n" +
	"\aCheckId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xcb\x01\n" +
	"\x06Checks\x123\n" +
	"\x06Create\x12\x13.checks.CheckCreate\x1a\x14.checks.CheckFailure\x12+\n" +
	"\x06Remove\x12\x0f.checks.CheckId\x1a\x10.common.Response\x12)\n" +
	"\x03Use\x12\x10.checks.CheckUse\x1a\x10.common.Response\x124\n" +
	"\rGetUserChecks\x12\t.users.Id\x1a\x18.checks.AllChecksFailureB\n" +
	"Z\b./checksb\x06proto3"

var (
	file_checks_service_proto_rawDescOnce sync.Once
	file_checks_service_proto_rawDescData []byte
)

func file_checks_service_proto_rawDescGZIP() []byte {
	file_checks_service_proto_rawDescOnce.Do(func() {
		file_checks_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checks_service_proto_rawDesc), len(file_checks_service_proto_rawDesc)))
	})
	return file_checks_service_proto_rawDescData
}

var file_checks_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_checks_service_proto_goTypes = []any{
	(*Check)(nil),                 // 0: checks.Check
	(*CheckFailure)(nil),          // 1: checks.CheckFailure
	(*AllChecks)(nil),             // 2: checks.AllChecks
	(*AllChecksFailure)(nil),      // 3: checks.AllChecksFailure
	(*CheckCreate)(nil),           // 4: checks.CheckCreate
	(*CheckUse)(nil),              // 5: checks.CheckUse
	(*CheckId)(nil),               // 6: checks.CheckId
	(common.Currency)(0),          // 7: common.Currency
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*common.Failure)(nil),        // 9: common.Failure
	(*users.Id)(nil),              // 10: users.Id
	(*common.Response)(nil),       // 11: common.Response
}
var file_checks_service_proto_depIdxs = []int32{
	7,  // 0: checks.Check.currency:type_name -> common.Currency
	8,  // 1: checks.Check.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 2: checks.CheckFailure.check:type_name -> checks.Check
	9,  // 3: checks.CheckFailure.failure:type_name -> common.Failure
	0,  // 4: checks.AllChecks.Checks:type_name -> checks.Check
	2,  // 5: checks.AllChecksFailure.allChecks:type_name -> checks.AllChecks
	9,  // 6: checks.AllChecksFailure.failure:type_name -> common.Failure
	7,  // 7: checks.CheckCreate.currency:type_name -> common.Currency
	4,  // 8: checks.Checks.Create:input_type -> checks.CheckCreate
	6,  // 9: checks.Checks.Remove:input_type -> checks.CheckId
	5,  // 10: checks.Checks.Use:input_type -> checks.CheckUse
	10, // 11: checks.Checks.GetUserChecks:input_type -> users.Id
	1,  // 12: checks.Checks.Create:output_type -> checks.CheckFailure
	11, // 13: checks.Checks.Remove:output_type -> common.Response
	11, // 14: checks.Checks.Use:output_type -> common.Response
	3,  // 15: checks.Checks.GetUserChecks:output_type -> checks.AllChecksFailure
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_checks_service_proto_init() }
func file_checks_service_proto_init() {
	if File_checks_service_proto != nil {
		return
	}
	file_checks_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_checks_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checks_service_proto_rawDesc), len(file_checks_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checks_service_proto_goTypes,
		DependencyIndexes: file_checks_service_proto_depIdxs,
		MessageInfos:      file_checks_service_proto_msgTypes,
	}.Build()
	File_checks_service_proto = out.File
	file_checks_service_proto_goTypes = nil
	file_checks_service_proto_depIdxs = nil
}
