-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS "Offers"  (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Type" SMALLINT NOT NULL CHECK("Type" = 0 OR "Type" = 1),
    "Name" TEXT NOT NULL UNIQUE,
    "Seller" BIGINT NOT NULL,
    "Cost" BIGINT NOT NULL CHECK ("Cost" >= 0),
    "UpForSaleAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS "Offers";
-- +goose StatementEnd
